Examen/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.views.generic import RedirectView

urlpatterns = [
    re_path(r'^$', RedirectView.as_view(pattern_name='inicio')),
    path('encuestas/', include('encuestas.urls')),
    path('admin/', admin.site.urls),
]

encuestas/urls.py
from django.urls import path
from encuestas import views

urlpatterns = [
    path('inicio/', views.inicio, name='inicio'),
    path('realizar-encuesta/', views.CreateEncuesta.as_view(), name='create-encuesta'),
]

encuestas/models.py
from django.db import models


# Create your models here.
class InteresPersonal(models.Model):
    value = models.CharField(max_length=50)

    class Meta:
        verbose_name_plural = 'Intereses Personales'

    def __str__(self):
        return self.value


class Encuesta(models.Model):
    MASCULINO = 'm'
    FEMENINO = 'f'
    SEX_CHOICES = [
        (MASCULINO, 'Masculino'),
        (FEMENINO, 'Femenino'),
    ]
    GRADOS_ESCOLARIDAD_CHOICES = [
        ('p', 'Primaria'),
        ('s', 'Secundaria'),
        ('tm', 'Técnico Medio'),
        ('pre', 'Preuniversitario'),
        ('ns', 'Nivel Superior'),
    ]

    nombre = models.CharField(max_length=100)
    edad = models.PositiveIntegerField()
    sexo = models.CharField(max_length=1, choices=SEX_CHOICES)
    grado_de_escolaridad = models.CharField(max_length=3, choices=GRADOS_ESCOLARIDAD_CHOICES)
    peso_corporal = models.FloatField(verbose_name='Peso corporal (Kg)')
    intereses_personales = models.ManyToManyField(InteresPersonal)


    def __str__(self):
        return 'Encuesta realizada por %s' % self.nombre

encuestas/forms.py
from django.core.exceptions import ValidationError
from django.forms import ModelForm, widgets

from encuestas.models import Encuesta


class EncuestaForm(ModelForm):
    class Meta:
        model = Encuesta
        fields = '__all__'
        widgets = {
            'nombre': widgets.TextInput(attrs={'class': 'form-control'}),
            'edad': widgets.NumberInput(attrs={'class': 'form-control', 'min': 10, 'max': 130}),
            'peso_corporal': widgets.NumberInput(attrs={'class': 'form-control', 'min': 20}),
            'sexo': widgets.Select(attrs={'class': 'form-select'}),
            'grado_de_escolaridad': widgets.Select(attrs={'class': 'form-select'}),
            'intereses_personales': widgets.CheckboxSelectMultiple(),
        }

    def clean_nombre(self):
        nombre = self.cleaned_data['nombre']
        if len(nombre.split()) < 3:
            raise ValidationError('Debe especificar su nombre completo, incluyendo ambos apellidos')
        return nombre.title()

    def clean_peso_corporal(self):
        peso = self.cleaned_data['peso_corporal']
        if peso <= 0:
            raise ValidationError('El peso debe ser un valor positivo')
        return peso

    def clean_edad(self):
        # Como no se especifica establecí un rango lo más lógico posible.
        edad = self.cleaned_data['edad']
        if edad < 10:
            raise ValidationError('Su edad debe ser mayor a 10 años')
        if edad > 130:
            raise ValidationError('Su edad debe ser menor a 130 años')
        return edad

encuestas/views.py
from django.contrib import messages
from django.shortcuts import render
# Create your views here.
from django.urls import reverse_lazy
from django.views.generic import CreateView

from encuestas.forms import EncuestaForm


def inicio(request):
    return render(request, 'encuestas/inicio.html')


class CreateEncuesta(CreateView):
    template_name = 'encuestas/create_encuesta.html'
    form_class = EncuestaForm
    success_url = reverse_lazy('inicio')

    def form_valid(self, form):
        messages.success(self.request, 'La encuesta se ha guardado satisfactoriamente.')
        return super(CreateEncuesta, self).form_valid(form)

encuestas/templates/encuestas/create_encuesta.html
{% extends 'base.html' %}

{% block content %}
    <div class="container-fluid d-flex mt-5">
        <div class="row justify-content-center">
            <div class="col-8 col-lg-6">
                <div class="card border-primary shadow">
                    <div class="card-header bg-primary text-center text-white">Realizar encuesta</div>
                    <div class="card-body">
                        <form class="row g-2" action="" method="post">
                            {% csrf_token %}
                            {% for error in form.non_field_errors %}
                                <div class="alert alert-danger mb-4" role="alert">
                                    <b>{{ error }}</b>
                                </div>
                            {% endfor %}

                            <div class="col-12">
                                <div class="form-floating mb-3">
                                    {{ form.nombre }}
                                    <label for="id_nombre">{{ form.nombre.label }}</label>
                                    {% if form.nombre.errors %}
                                        {% for error in form.nombre.errors %}
                                            <small style="color: red">{{ error }}</small>
                                        {% endfor %}
                                    {% endif %}
                                </div>
                            </div>
                            <div class="col-sm-6 form-floating">
                                {{ form.edad }}
                                <label>{{ form.edad.label }}</label>
                                {% if form.edad.errors %}
                                    {% for error in form.edad.errors %}
                                        <small style="color: red">{{ error }}</small>
                                    {% endfor %}
                                {% endif %}
                            </div>
                            <div class="col-sm-6 form-floating">
                                {{ form.sexo }}
                                <label>{{ form.sexo.label }}</label>
                                {% if form.sexo.errors %}
                                    {% for error in form.sexo.errors %}
                                        <small style="color: red">{{ error }}</small>
                                    {% endfor %}
                                {% endif %}
                            </div>
                            <div class="col-sm-6 form-floating">
                                {{ form.peso_corporal }}
                                <label>{{ form.peso_corporal.label }}</label>
                                {% if form.peso_corporal.errors %}
                                    {% for error in form.peso_corporal.errors %}
                                        <small style="color: red">{{ error }}</small>
                                    {% endfor %}
                                {% endif %}
                            </div>
                            <div class="col-sm-6 form-floating">
                                {{ form.grado_de_escolaridad }}
                                <label>{{ form.grado_de_escolaridad.label }}</label>
                                {% if form.grado_de_escolaridad.errors %}
                                    {% for error in form.grado_de_escolaridad.errors %}
                                        <small style="color: red">{{ error }}</small>
                                    {% endfor %}
                                {% endif %}
                            </div>
                            <div class="col-12 mb-3">
                                <label class="d-inline-block me-2">{{ form.intereses_personales.label }}:</label>
                                {% if form.intereses_personales.errors %}
                                    {% for error in form.intereses_personales.errors %}
                                        <small style="color: red">{{ error }}</small>
                                    {% endfor %}
                                {% endif %}
                                {{ form.intereses_personales }}
                            </div>
                            <div class="col text-center">
                                <input class="btn btn-primary" type="submit" value="Enviar" style="width: 10.5rem"/>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

encuestas/templates/encuestas/inicio.html
{% extends 'base.html' %}

{% block content %}
    <div class="container mt-3">
        <div class="row">
            <div class="col">
                <h1 class="text-center">Encuestas</h1>
            </div>
        </div>
        <div class="row ">
            <div class="col">
                <p class="text-center">Bienvenido, pulse
                    <a href="{% url 'create-encuesta' %}">aquí</a>
                    para realizar la encuesta.
                </p>
            </div>
        </div>
    </div>
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Encuestas</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
          crossorigin="anonymous">

</head>
<body>
{% if messages %}
    <ul class="bg-success">
        {% for message in messages %}
            <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
        {% endfor %}
    </ul>
{% endif %}
{% block content %}{% endblock %}

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
        crossorigin="anonymous"></script>
</body>
</html>